spring:
  application:
    name: price-monitor

  datasource:
    url: jdbc:sqlite:price-monitor.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
